---
- hosts: all
  become: yes
  vars:
   var1: apache2
   var2: present
   var3: absent
   var4: started
   var5: restarted
   var6: stopped
   var7: git
   var8: tree
   var9: wget
   var10: yes
   var11: no
   var12: directory
   var13: touch
  tasks:
  - include_tasks: include1.yml
  - name: cache update
    apt:
     update_cache: "{{var10}}"
  - name: installations
    apt:
     name: "{{ item }}"
     state: "{{var2}}"
    tags: 
    - packages
    ignore_errors: "{{var10}}"
    notify: restartwebserver
    loop:
     - "{{var1}}"
     - "{{var7}}"
     - "{{var8}}"
     - "{{var9}}"
  - name: directory creation
    file:
     path: /home/trinadh/sampledir
     state: "{{var12}}"
     recurse: "{{var10}}"
    tags:
    - directory
  - name: file creation
    file:
     path: /home/trinadh/sampledir/sample3.txt
     state: "{{var13}}"
     mode: u+rw,g-wx,o-rwx   
    tags:
    - file
  - name: content in a file
    lineinfile:
     path: /home/trinadh/sampledir/sample3.txt
     line: hi this is my first line in a file
  - name: block in a file 
    blockinfile:
     path: /home/trinadh/sampledir/sample3.txt
     block:
      <h1>  this is sample file that sates a newly changed file </h1>
  - name: creating sub-directories
    command:
     cmd: mkdir -p /home/trinadh/sampledir/sub-sampledir
  - name: file creation in subdir
    file:
     path: /home/trinadh/sampledir/sub-sampledir/sample10.txt
     state: "{{var13}}"
     mode: u+rw,g-wx,o-rwx
  - name: template to display
    template:
     src: template1.j2
     dest: /var/www/html/index.html  
    tags:
    - configuration
  - name:
    shell: echo "only on CentOS"
    when: ansible_os_family == "CentOS"
    tags: 
    - echo
  handlers:
  - name: restartwebserver
    service:
     name: "{{var1}}" 
     state: "{{var5}}"
 
   
