---
- hosts: all
  become: yes
  # gather_facts: false
  tasks:
  - name: install git on nodes
    apt:
     name: apache2
     state: absent
  - name: start git service
    service:
     name: apache2
     state: stopped
