---
- hosts: server
  become: yes
  tasks:
  - name: creating mountable folder
    file:
     path: /share
     state: directory
     mode: 777
     owner: root
     group: root
  - name: mount to have filesystem
    filesystem:
     fstype: ext4
     dev: "{{ mountable_share_drive | default('/dev/xvdb') }}"
  - name: set mountpoints
    mount:
     name: /share
     src: "{{ mountable_share_drive | default('/dev/xvdb') }}"
     fstype: auto
     opts: defaults,nobootwait
     dump: 0
     passno: 2
     state: mounted
  - name: nfs utilities installing
    apt:
     name: "{{ item }}"
     state: present
     update_cache: yes
    loop:
      - nfs-common
      - nfs-kernel-server
  - name: copying template
    template:
     src: exports.j2
     dest: /etc/exports
     owner: root
     group: root
  - name: restart nfs server
    service:
     name: nfs-kernel-server
     state: restarted


