---
- name: updating ubuntu
  apt:
<<<<<<< HEAD
   update_cache: yes
=======
   update_chache: yes
>>>>>>> dd20472650b5d0ce14911638ab856c884b37b0a7

- name: installing nfs-kernel-server
  apt:
   name: nfs-kernel-server 
   state: present

- name: making a shared directory
  file:
   path: /var/nfs/general
<<<<<<< HEAD
   state: present
=======
   state: directory
>>>>>>> dd20472650b5d0ce14911638ab856c884b37b0a7
   owner: nobody
   group: nogroup

- name: editing file for nfs-kernel-server
  template:
   src: templates/exports.j2
   dest: /etc/exports

- name: restarting nfs-kernel-server
  service:
   name: nfs-kernel-server
   state: restarted

<<<<<<< HEAD
- name: firewall permission
  ufw:
   state: enabled
   policy: allow

- name: allow openssh
   rule: allow
   name: OpenSSH

- name: allow nfs
   rule: allow
   name: nfs
   direction: in 
   src: 172.31.45.67
   from_port: 2049
   dest: 172.31.39.51
   to_port: 2049

=======
- name: command module
  command:
   cmd: sudo ufw allow from 172.31.33.244 to any port nfs


   
>>>>>>> dd20472650b5d0ce14911638ab856c884b37b0a7
